name: linting python code

on: push

jobs:
  python-linting-code:
    runs-on: ubuntu-latest

    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v6.2.0

      - name: Checkout code
        uses: action/checkout@v4
        with:
          fetch-depth: 2

            
